"""Modify schema of users_sqla

Revision ID: 2e7c987525f3
Revises: a08aa3723c82
Create Date: 2024-02-20 02:32:14.025138

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "2e7c987525f3"
down_revision = "a08aa3723c82"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users_sqla", schema=None) as batch_op:
        batch_op.alter_column(
            "username", existing_type=sa.VARCHAR(length=80), nullable=True
        )
        batch_op.alter_column(
            "last_active_date", existing_type=sa.DATE(), nullable=True
        )
        batch_op.drop_constraint("users_sqla_username_key", type_="unique")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users_sqla", schema=None) as batch_op:
        batch_op.create_unique_constraint("users_sqla_username_key", ["username"])
        batch_op.alter_column(
            "last_active_date", existing_type=sa.DATE(), nullable=False
        )
        batch_op.alter_column(
            "username", existing_type=sa.VARCHAR(length=80), nullable=False
        )

    op.create_table(
        "daily",
        sa.Column(
            "user_id", sa.VARCHAR(length=255), autoincrement=False, nullable=True
        ),
        sa.Column(
            "daily_xp",
            sa.INTEGER(),
            server_default=sa.text("0"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "daily_date",
            sa.DATE(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            autoincrement=False,
            nullable=True,
        ),
        sa.UniqueConstraint("user_id", "daily_date", name="user_daily_date_unique"),
    )
    op.create_table(
        "users",
        sa.Column(
            "user_id", sa.VARCHAR(length=256), autoincrement=False, nullable=False
        ),
        sa.Column(
            "username", sa.VARCHAR(length=255), autoincrement=False, nullable=True
        ),
        sa.Column("level", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("email", sa.VARCHAR(length=255), autoincrement=False, nullable=True),
        sa.Column("xp", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("last_active_date", sa.DATE(), autoincrement=False, nullable=True),
    )
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.create_index("unique_username", ["username"], unique=True)

    # ### end Alembic commands ###
