"""Rename daily_sqla columns

Revision ID: 532217683cea
Revises: 896b611dcd47
Create Date: 2024-02-19 23:45:51.747500

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "532217683cea"
down_revision = "896b611dcd47"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("daily_sqla", schema=None) as batch_op:
        batch_op.add_column(sa.Column("daily_date", sa.Date(), nullable=False))
        batch_op.add_column(sa.Column("daily_xp", sa.Integer(), nullable=False))
        batch_op.drop_column("xp")
        batch_op.drop_column("date")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("daily_sqla", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("date", sa.DATE(), autoincrement=False, nullable=False)
        )
        batch_op.add_column(
            sa.Column("xp", sa.INTEGER(), autoincrement=False, nullable=False)
        )
        batch_op.drop_column("daily_xp")
        batch_op.drop_column("daily_date")

    op.create_table(
        "daily",
        sa.Column(
            "user_id", sa.VARCHAR(length=255), autoincrement=False, nullable=True
        ),
        sa.Column(
            "daily_xp",
            sa.INTEGER(),
            server_default=sa.text("0"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "daily_date",
            sa.DATE(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            autoincrement=False,
            nullable=True,
        ),
        sa.UniqueConstraint("user_id", "daily_date", name="user_daily_date_unique"),
    )
    op.create_table(
        "users",
        sa.Column(
            "user_id", sa.VARCHAR(length=256), autoincrement=False, nullable=False
        ),
        sa.Column(
            "username", sa.VARCHAR(length=255), autoincrement=False, nullable=True
        ),
        sa.Column("level", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("email", sa.VARCHAR(length=255), autoincrement=False, nullable=True),
        sa.Column("xp", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("last_active_date", sa.DATE(), autoincrement=False, nullable=True),
    )
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.create_index("unique_username", ["username"], unique=True)

    # ### end Alembic commands ###
