"""Initial migration

Revision ID: 896b611dcd47
Revises: 
Create Date: 2024-02-19 22:58:37.397570

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "896b611dcd47"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users_sqla",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(length=80), nullable=False),
        sa.Column("email", sa.String(length=120), nullable=False),
        sa.Column("xp", sa.Integer(), nullable=False),
        sa.Column("level", sa.Integer(), nullable=False),
        sa.Column("last_active_date", sa.Date(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
        sa.UniqueConstraint("username"),
    )
    op.create_table(
        "daily_sqla",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("xp", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users_sqla.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "daily",
        sa.Column(
            "user_id", sa.VARCHAR(length=255), autoincrement=False, nullable=True
        ),
        sa.Column(
            "daily_xp",
            sa.INTEGER(),
            server_default=sa.text("0"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "daily_date",
            sa.DATE(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            autoincrement=False,
            nullable=True,
        ),
        sa.UniqueConstraint("user_id", "daily_date", name="user_daily_date_unique"),
    )
    op.create_table(
        "users",
        sa.Column(
            "user_id", sa.VARCHAR(length=256), autoincrement=False, nullable=False
        ),
        sa.Column(
            "username", sa.VARCHAR(length=255), autoincrement=False, nullable=True
        ),
        sa.Column("level", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("email", sa.VARCHAR(length=255), autoincrement=False, nullable=True),
        sa.Column("xp", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("last_active_date", sa.DATE(), autoincrement=False, nullable=True),
    )
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.create_index("unique_username", ["username"], unique=True)

    op.drop_table("daily_sqla")
    op.drop_table("users_sqla")
    # ### end Alembic commands ###
