"""Alter user_id to str

Revision ID: a08aa3723c82
Revises: ecb3b4365ca2
Create Date: 2024-02-20 00:34:35.140553

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "a08aa3723c82"
down_revision = "ecb3b4365ca2"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("daily_sqla", schema=None) as batch_op:
        batch_op.alter_column(
            "user_id",
            existing_type=sa.INTEGER(),
            type_=sa.String(length=256),
            existing_nullable=False,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("daily_sqla", schema=None) as batch_op:
        batch_op.alter_column(
            "user_id",
            existing_type=sa.String(length=256),
            type_=sa.INTEGER(),
            existing_nullable=False,
        )

    op.create_table(
        "daily",
        sa.Column(
            "user_id", sa.VARCHAR(length=255), autoincrement=False, nullable=True
        ),
        sa.Column(
            "daily_xp",
            sa.INTEGER(),
            server_default=sa.text("0"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "daily_date",
            sa.DATE(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            autoincrement=False,
            nullable=True,
        ),
        sa.UniqueConstraint("user_id", "daily_date", name="user_daily_date_unique"),
    )
    op.create_table(
        "users",
        sa.Column(
            "user_id", sa.VARCHAR(length=256), autoincrement=False, nullable=False
        ),
        sa.Column(
            "username", sa.VARCHAR(length=255), autoincrement=False, nullable=True
        ),
        sa.Column("level", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("email", sa.VARCHAR(length=255), autoincrement=False, nullable=True),
        sa.Column("xp", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("last_active_date", sa.DATE(), autoincrement=False, nullable=True),
    )
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.create_index("unique_username", ["username"], unique=True)

    # ### end Alembic commands ###
